plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
}

apply from: "../featureConfig.build.gradle"

android {
    namespace 'com.ls.home'

    defaultConfig {
    }

    buildFeatures {
        compose true
    }
}

dependencies {
    implementation project(":library_base")
}
